version: '3.7'
networks:
  backend:
    driver: ${NETWORKS_DRIVER}

services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:22.6-alpine
    environment:
      - CLICKHOUSE_INIT_TIMEOUT=600
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    volumes:
      - ./clickhouse_node/data/clickhouse:/var/lib/clickhouse
      - ./config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./users.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ports:
      - '8123:8123'
      - '8124:9000'
      - '8125:9009'
      - '8126:8126'
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    tty: true
